### ISSUE TITLE
[Suggestion] Split the evaporator into two tanks.

### ISSUE THREAD

**Issue by PapierZylinder** [VonZeeple/MapleSyrup-1.12.2#2]
In the current version 0.1.1-beta the evaporator only has one tank. This makes it impossible to automate the production of any liquid you want to produce in the evaporator, since every fluidpipe that doesn't have a filter option will pull out the sap or what the current input fluid is before the evaporator can convert it.

My suggestion is that the evaporator will have a input and output tank to prevent this behaviour.

**Comment by VonZeeple** [comment]
Hi, thx for your feedback. This is totally intentional and it won't change. You can still use a redstone timer to automate the process. Maybe in a future release i'll  add a second, more modern evaporator similar to ones used in actual sugar-shacks.

**Comment by VonZeeple** [comment]
Evaporator works as intended
